export default {
	USER_GET_DATA : 'USER_GET_DATA',
	USER_GET_DATA_SUCCESS : 'USER_GET_DATA_SUCCESS',
	USER_GET_DATA_FAIL : 'USER_GET_DATA_FAIL',
	IMAGE_GET : 'IMAGE_GET',
	IMAGE_GET_SUCCESS : 'IMAGE_GET_SUCCESS',
	IMAGE_GET_FAIL : 'IMAGE_GET_FAIL',
}